import { Train, PriorityAlert, ChatMessage } from './types';

export const INITIAL_TRAINS: Train[] = [
  {
    id: "RG-204",
    name: "InterCity Express [IC-402]",
    route: "Paris → Berlin",
    origin: "Paris",
    destination: "Berlin",
    status: "Optimal",
    delayMinutes: 5,
    currentSpeed: 184,
    powerEfficiency: 94.2,
    activeFaults: 0,
    crowdLevel: "Medium",
    crowdPercent: 58,
    safetyAlert: "Clear",
    riskScore: 12,
    sector: "Sector 7G",
    currentStation: "Grand Central",
    nextStop: "Oakwood St.",
    eta: "14:22",
    departureTime: "08:00",
    arrivalTime: "15:30",
    carCrowds: [30, 45, 88, 95, 55, 25, 15, 10],
    routeLegs: [
      { station: "Paris Gare du Nord", time: "08:00", status: "passed" },
      { station: "Brussels South", time: "09:45", status: "passed", delayNotes: "On Time" },
      { station: "Köln Hbf", time: "11:30", status: "passed", delayNotes: "+2m minor queue" },
      { station: "Grand Central Interchange", platform: "Platform 4", time: "13:15", status: "current" },
      { station: "Oakwood St.", time: "14:22", status: "upcoming", delayNotes: "Est. 14:22 (+5m)" },
      { station: "Berlin Hbf", time: "15:30", status: "upcoming" }
    ],
    aiRecommendation: "Acknowledge routine speed optimizer of +4 km/h through Sector 8 to recover remainder of the 5-minute minor dwell lag.",
    aiReasoning: "No mechanical friction anomalies. Track dry friction index is high. Forward clearances are verified via Sector 8 signal automation."
  },
  {
    id: "RG-882",
    name: "Caledonian Voyager [CV-082]",
    route: "London → Edinburgh",
    origin: "London",
    destination: "Edinburgh",
    status: "Optimal",
    delayMinutes: 0,
    currentSpeed: 210,
    powerEfficiency: 96.8,
    activeFaults: 0,
    crowdLevel: "Low",
    crowdPercent: 42,
    safetyAlert: "Clear",
    riskScore: 8,
    sector: "Sector 2A",
    currentStation: "Newcastle",
    nextStop: "Berwick-upon-Tweed",
    eta: "16:45",
    departureTime: "13:30",
    arrivalTime: "18:15",
    carCrowds: [20, 25, 30, 45, 50, 42, 28, 14],
    routeLegs: [
      { station: "London King's Cross", time: "13:30", status: "passed" },
      { station: "York", time: "15:10", status: "passed" },
      { station: "Newcastle Interchange", platform: "Platform 1", time: "16:15", status: "current" },
      { station: "Berwick-upon-Tweed", time: "16:45", status: "upcoming" },
      { station: "Edinburgh Waverley", time: "18:15", status: "upcoming" }
    ]
  },
  {
    id: "RG-401",
    name: "Trans-European Express [TE-990]",
    route: "Paris → Berlin",
    origin: "Paris",
    destination: "Berlin",
    status: "Critical",
    delayMinutes: 18,
    currentSpeed: 145,
    powerEfficiency: 82.1,
    activeFaults: 2,
    crowdLevel: "High",
    crowdPercent: 94,
    safetyAlert: "Critical",
    riskScore: 84,
    sector: "Sector 4G",
    currentStation: "Aachen West",
    nextStop: "Hannover Hbf",
    eta: "19:10",
    departureTime: "12:15",
    arrivalTime: "20:45",
    carCrowds: [85, 92, 98, 99, 94, 88, 72, 60],
    routeLegs: [
      { station: "Paris Gare de l'Est", time: "12:15", status: "passed" },
      { station: "Aachen West Terminal", platform: "Platform 2", time: "16:20", status: "current" },
      { station: "Hannover Hbf", time: "19:10", status: "upcoming", delayNotes: "delayed by track diagnostics" },
      { station: "Berlin Hbf", time: "20:45", status: "upcoming" }
    ],
    aiRecommendation: "Initiate immediate Level 2 axle thermal evaluation. Route non-essential cargo trains to northern bypass immediately.",
    aiReasoning: "Predictive monitoring indicates extreme 14% increase in axle vibrations and high heat indices on Carriage 4."
  },
  {
    id: "RG-112",
    name: "Shinkansen Bullet [SH-112]",
    route: "Tokyo → Osaka",
    origin: "Tokyo",
    destination: "Osaka",
    status: "Optimal",
    delayMinutes: 0,
    currentSpeed: 300,
    powerEfficiency: 98.9,
    activeFaults: 0,
    crowdLevel: "Medium",
    crowdPercent: 68,
    safetyAlert: "Clear",
    riskScore: 2,
    sector: "Sector 12J",
    currentStation: "Nagoya",
    nextStop: "Kyoto",
    eta: "11:55",
    departureTime: "10:15",
    arrivalTime: "12:35",
    carCrowds: [50, 60, 65, 75, 78, 68, 55, 40],
    routeLegs: [
      { station: "Tokyo Station", time: "10:15", status: "passed" },
      { station: "Shin-Yokohama", time: "10:33", status: "passed" },
      { station: "Nagoya Platform 14", time: "11:35", status: "current" },
      { station: "Kyoto", time: "11:55", status: "upcoming" },
      { station: "Shin-Osaka", time: "12:35", status: "upcoming" }
    ]
  },
  {
    id: "IR-224",
    name: "Vande Bharat Express [22436]",
    route: "New Delhi ↔ Varanasi",
    origin: "New Delhi",
    destination: "Varanasi",
    status: "Optimal",
    delayMinutes: 0,
    currentSpeed: 130,
    powerEfficiency: 95.8,
    activeFaults: 0,
    crowdLevel: "Medium",
    crowdPercent: 78,
    safetyAlert: "Clear",
    riskScore: 5,
    sector: "Sector IND-N1",
    currentStation: "Kanpur Central",
    nextStop: "Prayagraj Jn",
    eta: "12:00",
    departureTime: "06:00",
    arrivalTime: "14:00",
    carCrowds: [55, 68, 80, 85, 75, 70, 65, 50],
    routeLegs: [
      { station: "New Delhi Station", time: "06:00", status: "passed" },
      { station: "Kanpur Central Platform 1", time: "10:10", status: "current" },
      { station: "Prayagraj Jn", time: "12:00", status: "upcoming" },
      { station: "Varanasi Junction", time: "14:00", status: "upcoming" }
    ],
    aiRecommendation: "Maintain nominal cruise at 130 km/h. Forward blocks clear through Prayagraj sector.",
    aiReasoning: "Excellent track ballast conditions and optimal motor temperatures reported on all 16 coaches of the rake."
  },
  {
    id: "IR-129",
    name: "Mumbai Rajdhani Express [12952]",
    route: "New Delhi ↔ Mumbai Central",
    origin: "New Delhi",
    destination: "Mumbai Central",
    status: "Optimal",
    delayMinutes: 8,
    currentSpeed: 120,
    powerEfficiency: 92.4,
    activeFaults: 0,
    crowdLevel: "High",
    crowdPercent: 92,
    safetyAlert: "Clear",
    riskScore: 14,
    sector: "Sector IND-W4",
    currentStation: "Ratlam Jn",
    nextStop: "Vadodara Jn",
    eta: "05:15",
    departureTime: "16:55",
    arrivalTime: "08:35",
    carCrowds: [88, 92, 95, 96, 94, 90, 85, 70],
    routeLegs: [
      { station: "New Delhi Hazarat Nizamuddin", time: "16:55", status: "passed" },
      { station: "Kota Junction", time: "21:40", status: "passed" },
      { station: "Ratlam Junction Platform 3", time: "01:15", status: "current" },
      { station: "Vadodara Junction", time: "05:15", status: "upcoming" },
      { station: "Mumbai Central Gare", time: "08:35", status: "upcoming" }
    ]
  },
  {
    id: "IR-120",
    name: "Howrah Duronto Express [12246]",
    route: "Bengaluru ↔ Howrah",
    origin: "Bengaluru",
    destination: "Howrah",
    status: "Advisory",
    delayMinutes: 15,
    currentSpeed: 110,
    powerEfficiency: 89.1,
    activeFaults: 1,
    crowdLevel: "High",
    crowdPercent: 86,
    safetyAlert: "Clear",
    riskScore: 28,
    sector: "Sector IND-E2",
    currentStation: "Visakhapatnam",
    nextStop: "Bhubaneswar",
    eta: "11:20",
    departureTime: "11:00",
    arrivalTime: "16:15",
    carCrowds: [70, 80, 85, 90, 88, 82, 75, 60],
    routeLegs: [
      { station: "Siddharoodha Swamiji Hubballi", time: "11:00", status: "passed" },
      { station: "Vijayawada Junction", time: "22:30", status: "passed" },
      { station: "Visakhapatnam Junction Platform 8", time: "04:15", status: "current" },
      { station: "Bhubaneswar Terminal", time: "11:20", status: "upcoming" },
      { station: "Howrah Station", time: "16:15", status: "upcoming" }
    ],
    aiRecommendation: "Acknowledge 15-minute dwell delay due to signal line scheduling and minor coach power grid fluctuations.",
    aiReasoning: "Main alternator backup 2 active. Heavy passenger load of 86% increases air-conditioning compression overhead."
  },
  {
    id: "IR-201",
    name: "Bhopal Shatabdi Express [12002]",
    route: "New Delhi ↔ Bhopal Junction",
    origin: "New Delhi",
    destination: "Bhopal Junction",
    status: "Optimal",
    delayMinutes: 0,
    currentSpeed: 150,
    powerEfficiency: 96.5,
    activeFaults: 0,
    crowdLevel: "Medium",
    crowdPercent: 62,
    safetyAlert: "Clear",
    riskScore: 4,
    sector: "Sector IND-C2",
    currentStation: "Agra Cantt",
    nextStop: "Gwalior Jn",
    eta: "08:15",
    departureTime: "06:00",
    arrivalTime: "14:40",
    carCrowds: [45, 55, 68, 70, 65, 60, 52, 40],
    routeLegs: [
      { station: "New Delhi Station", time: "06:00", status: "passed" },
      { station: "Agra Cantt Platform 1", time: "07:50", status: "current" },
      { station: "Gwalior Junction", time: "09:30", status: "upcoming" },
      { station: "Jhansi Junction", time: "10:45", status: "upcoming" },
      { station: "Bhopal Junction Terminal", time: "14:40", status: "upcoming" }
    ],
    aiRecommendation: "Nominal telemetry profile. Auto-catenary tensioning parameters within green tolerances in central sector.",
    aiReasoning: "Standard passenger density and high performance on all LHB coaches evaluated."
  },
  {
    id: "IR-205",
    name: "Gatimaan Express [12050]",
    route: "Nizamuddin ↔ Jhansi Junction",
    origin: "Hazrat Nizamuddin",
    destination: "Jhansi Junction",
    status: "Optimal",
    delayMinutes: 0,
    currentSpeed: 160,
    powerEfficiency: 97.2,
    activeFaults: 0,
    crowdLevel: "Medium",
    crowdPercent: 55,
    safetyAlert: "Clear",
    riskScore: 3,
    sector: "Sector IND-N2",
    currentStation: "Hazrat Nizamuddin",
    nextStop: "Agra Cantt",
    eta: "09:50",
    departureTime: "08:10",
    arrivalTime: "12:35",
    carCrowds: [40, 50, 60, 65, 58, 52, 48, 35],
    routeLegs: [
      { station: "Hazrat Nizamuddin Platform 5", time: "08:10", status: "current" },
      { station: "Agra Cantt", time: "09:50", status: "upcoming" },
      { station: "Gwalior Junction", time: "11:15", status: "upcoming" },
      { station: "Jhansi Junction Terminal", time: "12:35", status: "upcoming" }
    ],
    aiRecommendation: "Authorize max cruise speed of 160 km/h as the Hazrat-Agra direct corridor reports no maintenance log blocks.",
    aiReasoning: "WAP-5 high-speed locomotive working with nominal traction values."
  },
  {
    id: "IR-210",
    name: "Deccan Queen [12124]",
    route: "Pune ↔ Mumbai CSMT",
    origin: "Pune",
    destination: "Mumbai CSMT",
    status: "Optimal",
    delayMinutes: 2,
    currentSpeed: 105,
    powerEfficiency: 94.0,
    activeFaults: 0,
    crowdLevel: "High",
    crowdPercent: 89,
    safetyAlert: "Clear",
    riskScore: 11,
    sector: "Sector IND-W1",
    currentStation: "Lonavala",
    nextStop: "Karjat",
    eta: "08:35",
    departureTime: "07:15",
    arrivalTime: "10:25",
    carCrowds: [80, 88, 92, 95, 90, 85, 78, 60],
    routeLegs: [
      { station: "Pune Junction", time: "07:15", status: "passed" },
      { station: "Shivajinagar", time: "07:25", status: "passed" },
      { station: "Lonavala Platform 2", time: "08:15", status: "current" },
      { station: "Karjat Junction", time: "09:05", status: "upcoming" },
      { station: "Kalyan Junction", time: "09:45", status: "upcoming" },
      { station: "Mumbai Chhatrapati Shivaji Maharaj Terminus", time: "10:25", status: "upcoming" }
    ],
    aiRecommendation: "Monitor braking hydraulic indices closely when descending Bhor Ghat incline sectors.",
    aiReasoning: "Heavy load factor of 89% adds load overhead to pushing-pulling dual-engine configuration."
  },
  {
    id: "IR-701",
    name: "MA-HSR Bullet Train [NHSRCL-01]",
    route: "Mumbai ↔ Ahmedabad",
    origin: "Mumbai",
    destination: "Ahmedabad",
    status: "Optimal",
    delayMinutes: 1,
    currentSpeed: 320,
    powerEfficiency: 99.4,
    activeFaults: 0,
    crowdLevel: "Low",
    crowdPercent: 35,
    safetyAlert: "Clear",
    riskScore: 2,
    sector: "Sector IND-HSR",
    currentStation: "Surat",
    nextStop: "Vadodara",
    eta: "14:50",
    departureTime: "13:45",
    arrivalTime: "15:45",
    carCrowds: [25, 30, 38, 42, 35, 30, 25, 20],
    routeLegs: [
      { station: "Mumbai Bandra Kurla Complex HSR", time: "13:45", status: "passed" },
      { station: "Thane HSR", time: "13:58", status: "passed" },
      { station: "Surat HSR Platform 3", time: "14:32", status: "current" },
      { station: "Vadodara HSR", time: "14:50", status: "upcoming" },
      { station: "Ahmedabad Sabarmati HSR Terminal", time: "15:45", status: "upcoming" }
    ],
    aiRecommendation: "Cruise locked at 320 km/h. Automated slab track temperature monitoring reporting ideal thresholds.",
    aiReasoning: "Japan-collaborative E5 Series Shinkansen platform demonstrating flawless power and overhead line interface parameters."
  },
  {
    id: "IR-215",
    name: "Tejas Express [22672]",
    route: "Madurai ↔ Chennai Egmore",
    origin: "Madurai",
    destination: "Chennai Egmore",
    status: "Optimal",
    delayMinutes: 4,
    currentSpeed: 110,
    powerEfficiency: 93.8,
    activeFaults: 0,
    crowdLevel: "Medium",
    crowdPercent: 70,
    safetyAlert: "Clear",
    riskScore: 6,
    sector: "Sector IND-S3",
    currentStation: "Trichy",
    nextStop: "Villupuram",
    eta: "18:10",
    departureTime: "15:00",
    arrivalTime: "21:15",
    carCrowds: [50, 60, 75, 82, 70, 65, 55, 45],
    routeLegs: [
      { station: "Madurai Junction", time: "15:00", status: "passed" },
      { station: "Dindigul Junction", time: "15:45", status: "passed" },
      { station: "Tiruchirappalli Junction Platform 4", time: "17:00", status: "current" },
      { station: "Villupuram Junction", time: "18:10", status: "upcoming" },
      { station: "Chennai Egmore Terminal", time: "21:15", status: "upcoming" }
    ],
    aiRecommendation: "Nominal scheduling performance. Track clearances ahead verified.",
    aiReasoning: "Excellent safety metric logging from onboard microprocessors."
  },
  {
    id: "IR-101",
    name: "Howrah Rajdhani Express [12301]",
    route: "Howrah ↔ New Delhi",
    origin: "Howrah Junction",
    destination: "New Delhi",
    status: "Optimal",
    delayMinutes: 0,
    currentSpeed: 130,
    powerEfficiency: 96.1,
    activeFaults: 0,
    crowdLevel: "High",
    crowdPercent: 88,
    safetyAlert: "Clear",
    riskScore: 5,
    sector: "Sector IND-E1",
    currentStation: "Dhanbad Jn",
    nextStop: "Gaya Jn",
    eta: "20:05",
    departureTime: "16:50",
    arrivalTime: "10:00",
    carCrowds: [75, 82, 88, 90, 85, 80, 75, 60],
    routeLegs: [
      { station: "Howrah Junction Platform 9", time: "16:50", status: "passed" },
      { station: "Dhanbad Junction Platform 2", time: "19:50", status: "current" },
      { station: "Gaya Junction", time: "22:15", status: "upcoming" },
      { station: "Prayagraj Junction", time: "02:10", status: "upcoming" },
      { station: "New Delhi Station Terminal", time: "10:00", status: "upcoming" }
    ],
    aiRecommendation: "Cruise optimized at 130 km/h. Automated interlocking logs report absolute clearance throughout NCR line blocks.",
    aiReasoning: "HOG (Head-On-Generation) system optimal, relieving standard active hotel-load generator friction coefficients."
  },
  {
    id: "IR-208",
    name: "Patna Vande Bharat Express [22348]",
    route: "Patna ↔ Howrah",
    origin: "Patna Junction",
    destination: "Howrah Junction",
    status: "Optimal",
    delayMinutes: 3,
    currentSpeed: 110,
    powerEfficiency: 95.2,
    activeFaults: 0,
    crowdLevel: "Medium",
    crowdPercent: 68,
    safetyAlert: "Clear",
    riskScore: 4,
    sector: "Sector IND-M5",
    currentStation: "Asansol Jn",
    nextStop: "Howrah Junction",
    eta: "14:35",
    departureTime: "08:00",
    arrivalTime: "14:35",
    carCrowds: [40, 52, 60, 68, 70, 65, 58, 48],
    routeLegs: [
      { station: "Patna Junction Platform 1", time: "08:00", status: "passed" },
      { station: "Mokama Junction", time: "09:05", status: "passed" },
      { station: "Jasidih Junction", time: "11:10", status: "passed" },
      { station: "Asansol Junction Platform 5", time: "12:35", status: "current" },
      { station: "Howrah Junction Terminal", time: "14:35", status: "upcoming" }
    ],
    aiRecommendation: "Apply +5 km/h auxiliary traction drive through Raniganj mining zone track block corridors.",
    aiReasoning: "Nominal braking temperatures on LHB disk assemblies allow high thermal buffer on current descent."
  },
  {
    id: "IR-122",
    name: "Pune Duronto Express [12222]",
    route: "Howrah ↔ Pune Junction",
    origin: "Howrah Junction",
    destination: "Pune Junction",
    status: "Advisory",
    delayMinutes: 22,
    currentSpeed: 95,
    powerEfficiency: 88.4,
    activeFaults: 1,
    crowdLevel: "High",
    crowdPercent: 82,
    safetyAlert: "Clear",
    riskScore: 24,
    sector: "Sector IND-C8",
    currentStation: "Nagpur Jn",
    nextStop: "Bhusaval Jn",
    eta: "14:15",
    departureTime: "08:20",
    arrivalTime: "09:45",
    carCrowds: [62, 70, 80, 85, 88, 86, 78, 60],
    routeLegs: [
      { station: "Howrah Junction Platform 21", time: "08:20", status: "passed" },
      { station: "Bilaspur Junction", time: "15:45", status: "passed" },
      { station: "Nagpur Junction Platform 3", time: "22:10", status: "current" },
      { station: "Bhusaval Junction", time: "03:55", status: "upcoming" },
      { station: "Pune Junction Terminal", time: "09:45", status: "upcoming" }
    ],
    aiRecommendation: "Maintain active thermal sensor polling on Car 3 traction secondary motor. Set advisory delay tracking to +22m.",
    aiReasoning: "Vibration frequency reports minor ball-bearing noise under heavy passenger weight of 82%."
  },
  {
    id: "RG-502",
    name: "Eurostar High-Speed [ES-901]",
    route: "London ↔ Paris",
    origin: "London",
    destination: "Paris",
    status: "Optimal",
    delayMinutes: 0,
    currentSpeed: 290,
    powerEfficiency: 98.2,
    activeFaults: 0,
    crowdLevel: "Medium",
    crowdPercent: 64,
    safetyAlert: "Clear",
    riskScore: 3,
    sector: "Sector Channel-E3",
    currentStation: "Calais-Fréthun",
    nextStop: "Paris Nord",
    eta: "18:30",
    departureTime: "16:20",
    arrivalTime: "18:30",
    carCrowds: [40, 50, 65, 74, 68, 60, 55, 30],
    routeLegs: [
      { station: "London St Pancras Intl", time: "16:20", status: "passed" },
      { station: "Ashford International", time: "16:50", status: "passed" },
      { station: "Channel Tunnel Ingress", time: "17:15", status: "passed" },
      { station: "Calais-Fréthun Platform A", time: "17:50", status: "current" },
      { station: "Paris Gare du Nord Terminal", time: "18:30", status: "upcoming" }
    ]
  }
];

export const INITIAL_ALERTS: PriorityAlert[] = [
  {
    id: "alert-001",
    type: "engineering",
    title: "Track Inspection Needed",
    description: "Vibration sensors at Sector 4G reporting anomalies outside safety thresholds.",
    criticality: "High",
    associatedTrainId: "RG-401"
  },
  {
    id: "alert-002",
    type: "groups",
    title: "Platform Overcrowding",
    description: "Platform 9 is at 115% capacity. Suggested passenger flow redirection active.",
    criticality: "Mid"
  },
  {
    id: "alert-003",
    type: "alt_route",
    title: "Route Congestion",
    description: "Minor bottleneck forming at junction KB-9 due to weather-related speed limits.",
    criticality: "Low"
  }
];

export const INITIAL_CHAT: ChatMessage[] = [
  {
    id: "chat-001",
    sender: "user",
    text: "Which train is most at risk today?",
    timestamp: "09:14 AM"
  },
  {
    id: "chat-002",
    sender: "ai",
    text: "",
    timestamp: "09:14 AM",
    cardData: {
      title: "Immediate Attention Required: Train RG-401",
      isCritical: true,
      recommendation: "Initiate a Level 2 safety inspection at Sector 4G (Aachen West) and reroute non-essential freight via the northern loop.",
      reasoning: "Predictive sensors indicate a 14% increase in axle vibration and a pending thermal threshold breach on carriage 4. Peak congestion at 11:00 AM creates a high-collision probability if standard route is maintained.",
      associatedTrainId: "RG-401",
      showRerouteButton: true
    }
  },
  {
    id: "chat-003",
    sender: "user",
    text: "Why is Train RG-401 delayed? Give me the specific logistics breakdown.",
    timestamp: "09:16 AM"
  },
  {
    id: "chat-004",
    sender: "ai",
    text: "",
    timestamp: "09:16 AM",
    timelineData: {
      title: "Operational Delay Breakdown: RG-401",
      delayLabel: "+18M DELAY",
      steps: [
        { time: "08:45 AM", type: "EXTERNAL FACTOR", desc: "Unscheduled maintenance check on Track 4 prevented timely platform clearing.", icon: "construction" },
        { time: "09:10 AM", type: "RECOVERY PROTOCOL", desc: "RailGuard AI suggested localized speed optimization (+12km/h) to recover 6 minutes of the lost window.", icon: "speed" }
      ],
      statusNote: "Crew notified. Automatic switch logs locked and updated for optimized 19:10 arrival at Hannover."
    }
  }
];
